# Generated by Django 5.2.5 on 2025-08-19 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employee_department_alter_employee_grade_step_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeededuction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeededuction',
            name='deduction_type',
        ),
        migrations.RemoveField(
            model_name='employeededuction',
            name='employee_id',
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.allowancetype')),
            ],
            options={
                'unique_together': {('id', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.deductiontype')),
            ],
            options={
                'unique_together': {('id', 'amount')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
        migrations.DeleteModel(
            name='EmployeeDeduction',
        ),
    ]
