# Generated by Django 5.2.5 on 2025-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employeededuction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
